{
    'name': 'Real Estate',
    'version': '1.0',
    'summary': 'A Ready To Use Module For Real Estate Business',
    'category': 'Tutorial',
    'author': 'Zuhair',
    'depends': ['base','account'],
    'sequence': 1,
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/estate_security.xml',
        'views/estate_property_views.xml',
        'views/estate_property_offer_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_property_tag_views.xml',
        'views/res_users_views.xml',
        'views/estate_menus.xml',
    ],
    'installable': True,
    'application': True,
}
